services:
  app:
    image: searxng/searxng:2025.12.12-920b40253@sha256:b88ef002ab1d9a901766f9eb59779089a74e8f444477e0151fa8cd1f91a02006
    container_name: searxng-app
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - /etc/searxng:/etc/searxng
      - data:/var/cache/searxng
    ports:
      - "9006:8080"

volumes:
  data:
