services:
  app:
    image: ghcr.io/muety/wakapi:2.17.1@sha256:01187ba279e24ad46844b38cbfec1a150f6e87556f391f8a0a454881f0f7b138
    container_name: wakapi-app
    restart: unless-stopped
    ports:
      - 9008:3000
    env_file: .env

  db:
    image: postgres:17@sha256:bac8128cd62a35471a1e97966861aa2ac88c8d2f408767a425ae70695a607c99
    container_name: wakapi-db
    restart: unless-stopped
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
