services:
  app:
    image: ghcr.io/muety/wakapi:2.17.0@sha256:c75fd26fb3265eb5325ac46ef7e0c954becdc76db3291f449840b7d04dfcec3a
    container_name: wakapi-app
    restart: unless-stopped
    ports:
      - 9008:3000
    env_file: .env

  db:
    image: postgres:17@sha256:7352e0c4d62bbac8aa69d95e40220a60967c4a19f9c4f65b4d118175f7ce9e3b
    container_name: wakapi-db
    restart: unless-stopped
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
