services:
  app:
    image: ghcr.io/moghtech/komodo-core:1.19.5
    container_name: komodo-app
    labels:
      komodo.skip:
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 9012:9120
    env_file:
      - stack.env
    environment:
      KOMODO_DATABASE_ADDRESS: mongo:27017
      KOMODO_DATABASE_USERNAME: ${KOMODO_DB_USERNAME}
      KOMODO_DATABASE_PASSWORD: ${KOMODO_DB_PASSWORD}
    volumes:
      - /etc/komodo/backups:/backups
      - /etc/komodo/syncs:/syncs

  db:
    image: mongo:8.2.3
    container_name: komodo-db
    hostname: mongo
    expose:
      - 27017
    labels:
      komodo.skip:
    command: --quiet --wiredTigerCacheSizeGB 0.25
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    env_file:
      - stack.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${KOMODO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${KOMODO_DB_PASSWORD}

  periphery:
    image: ghcr.io/moghtech/komodo-periphery:1.19.5
    container_name: komodo-periphery
    labels:
      komodo.skip:
    restart: unless-stopped
    env_file:
      - stack.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - /etc/komodo:/etc/komodo

volumes:
  mongo_data:
  mongo_config:
