services:
  app:
    image: yourls:1.10.2@sha256:4fe1da1995d30c728e78b28e644796ae798e2c9fe0f83657ae10cfebb9adebe8
    container_name: yourls-app
    restart: always
    depends_on:
      - db
    ports:
      - 9004:8080
    env_file:
      - .env

  db:
    image: mysql:9.5.0@sha256:c9f0c66a87356518d4b30dbc065eb4567e4a04aff4d0ff194dea0973e5985b57
    container_name: yourls-db
    hostname: mysql
    restart: always
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
