services:
  app:
    image: yourls:1.10.3@sha256:1ccf9e3bf7be2ca8a5d73923b9b4b3e32244b0939a13c80904ce196c96852e89
    container_name: yourls-app
    restart: always
    depends_on:
      - db
    ports:
      - 9004:8080
    env_file:
      - .env

  db:
    image: mysql:9.5.0@sha256:c9f0c66a87356518d4b30dbc065eb4567e4a04aff4d0ff194dea0973e5985b57
    container_name: yourls-db
    hostname: mysql
    restart: always
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
