services:
  app:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n-app
    restart: unless-stopped
    ports:
      - "9006:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Singapore
      - TZ=Asia/Singapore
    env_file:
      - stack.env
    volumes:
      - data:/home/node/.n8n
      - ./local-files:/files

volumes:
  data:
