services:
  app:
    image: docker.n8n.io/n8nio/n8n:2.1.4@sha256:85214df20cd7bc020f8e4b0f60f87ea87f0a754ca7ba3d1ccdfc503ccd6e7f9c
    container_name: n8n-app
    restart: unless-stopped
    ports:
      - "9006:5678"
    env_file:
      - stack.env
    volumes:
      - data:/home/node/.n8n
      - files:/files

volumes:
  data:
  files:
