services:
  app:
    image: louislam/uptime-kuma:2@sha256:4c364ef96aaddac7ec4c85f5e5f31c3394d35f631381ccbbf93f18fd26ac7cba
    container_name: uptime_kuma-app
    restart: unless-stopped
    volumes:
      - data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "9007:3001"

volumes:
  data:
