services:
  app:
    image: fireflyiii/core:version-6.4.9@sha256:5252c462d3c1ed337dc87482c95bc62c25153d2a71ab87aed1c7e67e4a85d850
    hostname: app
    container_name: firefly-app
    restart: always
    volumes:
      - upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - "9002:8080"
    depends_on:
      - db

  db:
    image: mariadb:12.1.2@sha256:f54db0cb3ccfe9431aba6d08c65a1763c499789b116b4cb651dd7fcf325965b3
    hostname: db
    container_name: firefly-db
    restart: always
    env_file: .env
    volumes:
      - db:/var/lib/mysql

  # importer:
  #   image: fireflyiii/data-importer:version-1.9.1-cli
  #   hostname: importer
  #   restart: always
  #   container_name: firefly-importer
  #   ports:
  #     - "9003:8080"
  #   depends_on:
  #     - app
  #   env_file: .env

  cron:
    image: alpine:3.23.2@sha256:865b95f46d98cf867a156fe4a135ad3fe50d2056aa3f25ed31662dff6da4eb62
    container_name: firefly-cron
    restart: always
    env_file: .env
    command: sh -c "
      apk add tzdata && \
      (ln -fs /usr/share/zoneinfo/$$TZ /etc/localtime || true) && \
      echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/$$STATIC_CRON_TOKEN;echo\"
      | crontab - && \
      crond -f -L /dev/stdout"
    depends_on:
      - app

volumes:
  upload:
  db:
