services:
  app:
    image: docker.n8n.io/n8nio/n8n:2.4.2@sha256:f86ab8f8b22e61a7dbdcf8caccd35acc627516163f151dd2076d1ebde058bead
    container_name: n8n-app
    restart: unless-stopped
    ports:
      - "9001:5678"
    env_file:
      - .env
    volumes:
      - data:/home/node/.n8n
      - files:/files

volumes:
  data:
  files:
