services:
  app:
    image: docker.n8n.io/n8nio/n8n:2.6.1@sha256:f3214c30a15cd94eb55b3bc6400c402e38e43175f57c678bebc56091a72b73f3
    container_name: n8n-app
    restart: unless-stopped
    ports:
      - "9001:5678"
    env_file:
      - .env
    volumes:
      - data:/home/node/.n8n
      - files:/files

volumes:
  data:
  files:
