services:
  app:
    image: docker.n8n.io/n8nio/n8n:2.8.1@sha256:893cfe024fc3eff638be14565b0992dba1021108ec5b3069ba9eb1a57766d183
    container_name: n8n-app
    restart: unless-stopped
    ports:
      - "9001:5678"
    env_file:
      - .env
    volumes:
      - data:/home/node/.n8n
      - files:/files

volumes:
  data:
  files:
