services:
  app:
    image: docker.n8n.io/n8nio/n8n:2.4.1@sha256:0b9fec8449aa22aac16e89c6b361e5e4ae452499b386a01fc124d3c4f39b1001
    container_name: n8n-app
    restart: unless-stopped
    ports:
      - "9001:5678"
    env_file:
      - .env
    volumes:
      - data:/home/node/.n8n
      - files:/files

volumes:
  data:
  files:
