services:
  app:
    image: docker.n8n.io/n8nio/n8n:2.9.0@sha256:9485b779499c1680f80e992124ddbcae51b5bee4dd9d579d0057eb561a69d374
    container_name: n8n-app
    restart: unless-stopped
    ports:
      - "9001:5678"
    env_file:
      - .env
    volumes:
      - data:/home/node/.n8n
      - files:/files

volumes:
  data:
  files:
