services:
  app:
    image: docker.n8n.io/n8nio/n8n:2.10.0@sha256:7376bc277009ff684b27f9090aab385fd7faf0a4e029902587790a61d1633c3c
    container_name: n8n-app
    restart: unless-stopped
    ports:
      - "9001:5678"
    env_file:
      - .env
    volumes:
      - data:/home/node/.n8n
      - files:/files

volumes:
  data:
  files:
