services:
  app:
    image: docker.n8n.io/n8nio/n8n:2.3.2@sha256:aba343e23c1c757c535c73f33f1b7a5c940b1495d8910bf6cde9c2b5e4ac53a7
    container_name: n8n-app
    restart: unless-stopped
    ports:
      - "9001:5678"
    env_file:
      - .env
    volumes:
      - data:/home/node/.n8n
      - files:/files

volumes:
  data:
  files:
