services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun:latest@sha256:7b1dafa3d25cfd891deae52c7973c499f619f7d8eac52fad84f9aa1e5e6e01ca
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 7878:7878
      - 8989:8989
      - 6767:6767
      - 8080:8080
      - 8096:8096
      - 9696:9696
    env_file:
      - .env

  qbittorent:
    container_name: qbittorent
    image: ghcr.io/hotio/qbittorrent:release-v5.1.4@sha256:95794be129a684c6ca0a3073587e716746c3bfea6cf64342a6457fd9b0c109f2
    logging:
      driver: json-file
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Asia/Singapore
      - WEBUI_PORT=8080/tcp
      - LIBTORRENT=v1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/qbittorrent/config:/config
      - /mnt/sda/data/media:/data

  jellyfin:
    container_name: jellyfin
    image: ghcr.io/hotio/jellyfin:release-v10.11.5@sha256:b80c3f704d9eb48cee71f16cb903ff999cae229ae20bc1625b37361bf1c64662
    logging:
      driver: json-file
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Asia/Singapore
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/jellyfin/config:/config
      - /mnt/sda/data/media:/data

  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:release-6.0.4.10291@sha256:b6cf4a5c2f8c27b999e8592dd3d48b1fe5cd207a43351cd39c6f5de537eff414
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Asia/Singapore
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/radarr/config:/config
      - /mnt/sda/data/media:/data

  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:release-4.0.16.2944@sha256:9c4f4341b5035ee1e1861a31fe980ff869ffffdb72deace4844c6a5268a113ac
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Asia/Singapore
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/sonarr/config:/config
      - /mnt/sda/data/media:/data

  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:release-v1.5.4@sha256:6559fb927565dd2a374c60c15010d9a95ab9f8d744353b1117879bca4f9b8a6d
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Asia/Singapore
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/bazarr/config:/config
      - /mnt/sda/data/media/media:/data/media

  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr:release-2.3.0.5236@sha256:b2269c4910306300bb8e8c26097ef1e3834eec59eedb05c0fd0daa58d133dbe2
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Asia/Singapore
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/prowlarr/config:/config
