services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 7878:7878
      - 8989:8989
      - 6767:6767
      - 8080:8080
      - 8096:8096
    env_file:
      - .env

  qbittorent:
    container_name: qbittorent
    image: ghcr.io/hotio/qbittorrent:release-v5.1.4
    logging:
      driver: json-file
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Asia/Singapore
      - WEBUI_PORT=8080/tcp
      - LIBTORRENT=v1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/qbittorrent/config:/config
      - /mnt/sda/data/media:/data

  jellyfin:
    container_name: jellyfin
    image: ghcr.io/hotio/jellyfin:release-v10.11.5
    logging:
      driver: json-file
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Asia/Singapore
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/jellyfin/config:/config
      - /mnt/sda/data/media:/data

  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:release-6.0.4.10291
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Asia/Singapore
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/radarr/config:/config
      - /mnt/sda/data/media:/data

  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:release-4.0.16.2944
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Asia/Singapore
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/sonarr/config:/config
      - /mnt/sda/data/media:/data

  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:release-v1.5.4
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Asia/Singapore
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/bazarr/config:/config
      - /mnt/sda/data/media/media:/data/media
