services:
  app:
    image: glanceapp/glance:v0.8.4@sha256:6df86a7e8868d1eda21f35205134b1962c422957e42a0c44d4717c8e8f741b1a
    container_name: glance-app
    restart: unless-stopped
    volumes:
      - /etc/glance/config:/app/config
    ports:
      - 9000:8080
