services:
  server:
    image: vaultwarden/server:1.35.2@sha256:d89a6d21e361254670c24a4272b4b5f245e402c284f2f55de2c379fdbcfa1fa5
    container_name: vaultwarden-server
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - data:/data/
    ports:
      - 9012:80

volumes:
  data:
