services:
  server:
    image: vaultwarden/server:1.35.4@sha256:43498a94b22f9563f2a94b53760ab3e710eefc0d0cac2efda4b12b9eb8690664
    container_name: vaultwarden-server
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - data:/data/
    ports:
      - 9012:80

volumes:
  data:
