services:
  app:
    image: searxng/searxng:2025.12.12-920b40253
    container_name: searxng-app
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - /etc/searxng:/etc/searxng
      - data:/var/cache/searxng
    ports:
      - "9006:8080"

volumes:
  data:
