services:
  app:
    image: ghcr.io/bluewave-labs/checkmate-backend-mono:latest@sha256:d30ea8123766f32545a57d7dcac73e4b38e9c17560ee8ca2e76f5bc87f8eccde
    container_name: checkmate-app
    pull_policy: always
    restart: always
    ports:
      - "9009:52345"
    env_file: .env
    depends_on:
      - db

  db:
    image: ghcr.io/bluewave-labs/checkmate-mongo:latest@sha256:4546b02a1d232ae346bbc5c46659597203aa67701932aa5012d01c5cc2048435
    container_name: checkmate-db
    hostname: mongodb
    restart: always
    command: ["mongod", "--quiet", "--bind_ip_all"]
    volumes:
      - data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--quiet"]
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30

volumes:
  data:
