services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly-app
    restart: always
    volumes:
      - upload:/var/www/html/storage/upload
    env_file: stack.env
    ports:
      - "9002:8080"
    depends_on:
      - db

  db:
    image: mariadb:lts
    hostname: db
    container_name: firefly-db
    restart: always
    env_file: stack.env
    volumes:
      - db:/var/lib/mysql

  importer:
    image: fireflyiii/data-importer:latest
    hostname: importer
    restart: always
    container_name: firefly-importer
    ports:
      - "9003:8080"
    depends_on:
      - app
    env_file: stack.env

  cron:
    image: alpine
    container_name: firefly-cron
    restart: always
    env_file: stack.env
    command: sh -c "
      apk add tzdata && \
      (ln -fs /usr/share/zoneinfo/$$TZ /etc/localtime || true) && \
      echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/$$STATIC_CRON_TOKEN;echo\"
      | crontab - && \
      crond -f -L /dev/stdout"
    depends_on:
      - app
volumes:
  upload:
  db:
