services:
  app:
    image: codeberg.org/forgejo/forgejo:13@sha256:88858e7f592f82d4f650713c7bed8c0cd792d7f71475a7467c5650a31cd2eda9
    container_name: forgejo-app
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9006:3000"
      - "222:22"

volumes:
  data:
