services:
  app:
    image: ghcr.io/open-webui/open-webui:v0.8.2@sha256:7b7d324724ea4aa95d206362d8e9332544f11be167cd254ff83af9ab75734db8
    container_name: open_webui-app
    ports:
      - 9000:8080
    volumes:
      - data:/app/backend/data
    env_file:
      - .env
    restart: always

volumes:
  data:
