services:
  app:
    image: ghcr.io/open-webui/open-webui:v0.6.43
    container_name: open_webui-app
    ports:
      - 9000:8080
    volumes:
      - data:/app/backend/data
    env_file:
      - .env
    restart: always

volumes:
  data:
