services:
  app:
    image: ghcr.io/open-webui/open-webui:0.7.1@sha256:d9c509017a46ac0713aa5d94101fd10ea53fbaf9582627216026666257b115ee
    container_name: open_webui-app
    ports:
      - 9000:8080
    volumes:
      - data:/app/backend/data
    env_file:
      - .env
    restart: always

volumes:
  data:
