services:
  app:
    image: codeberg.org/readeck/readeck:0.21.6@sha256:60d5e93666dcf7dbb454a10ee5f6292bfc8f08ecc27f06bd898559cf4e851b6c
    container_name: readeck-app
    depends_on:
      db:
        condition: service_healthy
        restart: true
    ports:
      - 9011:8000
    env_file:
      - .env
    volumes:
      - data:/readeck
    restart: always
    healthcheck:
      test: ["CMD", "/bin/readeck", "healthcheck", "-config", "config.toml"]
      interval: 30s
      timeout: 2s
      retries: 3

  db:
    image: postgres:17@sha256:1eada89ec2521ae0f61125f6bdaf83bbbf88a43fecda48d112a83bb92df75c36
    container_name: readeck-db
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "readeck", "-d", "readeck"]
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
  data:
  pg_data:
