services:
  app:
    image: ghcr.io/wasi-master/13ft:1.3.0@sha256:fffe1204b1c8fac520fc456cad64f0ec74702047e7dae54052e1d71e4ff24088
    container_name: 13ft-app
    hostname: 13ft
    restart: unless-stopped
    ports:
      - "9003:5000"
