services:
  app:
    image: bentopdf/bentopdf-simple:latest@sha256:ed728002dede243e99da3b5f66a88ef4aa842962d5fc1313a75ab841cc9af237
    container_name: bento-app
    restart: unless-stopped
    ports:
      - "9007:8080"
