services:
  app:
    image: bentopdf/bentopdf-simple:latest@sha256:883f7b25ec62907d393e1e912d72aa8ab04147683f941eef8e054b7de1f0141d
    container_name: bento-app
    restart: unless-stopped
    ports:
      - "9007:8080"
