services:
  app:
    image: ghcr.io/muety/wakapi:2.17.0@sha256:c75fd26fb3265eb5325ac46ef7e0c954becdc76db3291f449840b7d04dfcec3a
    container_name: wakapi-app
    restart: unless-stopped
    ports:
      - 9008:3000
    env_file: stack.env

  db:
    image: postgres:17@sha256:6a2fb9aaf22abf4c5aeeeb8fcd12dfb57b7531d8d5196f90cfe0ce3f68c4c13f
    container_name: wakapi-db
    restart: unless-stopped
    env_file: stack.env
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
