services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome:v0.107.71@sha256:92929135ced2554aaf94706f766a98ad348f211df61b0704e2db7e8498cc00b7
    network_mode: host
    volumes:
      - /etc/adguard/work:/opt/adguardhome/work
      - /etc/adguard/conf:/opt/adguardhome/conf
    restart: always
